core/urls.py
from django.contrib import admin
from django.urls import path, include
from common import views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static
schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("sign-in/", views.LoginView.as_view(), name="sign-in"), 
    path("sign-out/", views.LogoutView.as_view(), name="sign-out"), 

    path('', include("common.urls")),
    path('manager/', include("manager.urls")),
    path('reception/', include("reception.urls")),
    path('accountant/', include("accountant.urls")),
    path('teacher/', include("teacher.urls")),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path("__debug__/", include("debug_toolbar.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path, include
from manager import views

app_name = "manager"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("archive/", views.Archive_list_view, name="archive_list"),
    path("manager/settings/<int:pk>/", views.Settings.as_view(), name="group-settings"),


    path('manager/user/',views.UserListView.as_view(),name='user-list'),
    path('manager/user/create/',views.UserCreateView.as_view(),name='user-create'),
    path('manager/user/<int:pk>/update/',views.UserUpdateView.as_view(),name='user-update'),
    path('manager/user/<int:pk>/delete/',views.UserDeleteView.as_view(),name='user-delete'),

    path("api/attendance/", views.AttendanceListAPIView.as_view(), name="attendance-list"),
    path("api/attendance/save/", views.SaveAttendanceAPIView.as_view(), name="save-attendance"),
    path("attendance/<int:group_id>/", views.AttendanceView.as_view(), name="attendance-page"),
    path("api/groups/<int:group_id>/students/", views.GroupStudentsAPIView.as_view(), name="group-students"),

    path("user/list/", views.UserListView.as_view(), name="user-list"),
    path("user/create/", views.UserCreateView.as_view(), name="user-create"),
    path("user/<int:pk>/update/", views.UserUpdateView.as_view(), name="user-update"),
    path("user/<int:pk>/delete/", views.UserDeleteView.as_view(), name="user-delete"),

    path("teacher/list/", views.TeacherListView.as_view(), name="teacher-list"),
    path("teacher/create/", views.TeacherCreateView.as_view(), name="teacher-create"),
    path("teacher/<int:pk>/update/", views.TeacherUpdateView.as_view(), name="teacher-update"),
    path("teacher/<int:pk>/delete/", views.TeacherDeleteView.as_view(), name="teacher-delete"),

    path("course/list/", views.CourseListView.as_view(), name="course-list"),
    path("course/create/", views.CourseCreateView.as_view(), name="course-create"),
    path("courses/<int:pk>/groups/", views.CourseGroupListView.as_view(), name="course-groups"),
    path("course/<int:pk>/update/", views.CourseUpdateView.as_view(), name="course-update"),
    path("course/<int:pk>/delete/", views.CourseDeleteView.as_view(), name="course-delete"),

    path("group/list/", views.GroupListView.as_view(), name="group-list"),
    path("group/create/", views.GroupCreateView.as_view(), name="group-create"),
    path("groups/<int:pk>/students/", views.group_students, name="group-students"),
    path("group/<int:pk>/update/", views.GroupUpdateView.as_view(), name="group-update"),
    path("group/<int:pk>/delete/", views.GroupDeleteView.as_view(), name="group-delete"),
    path("group/<int:pk>/detail/", views.GroupDetailView.as_view(), name="group-detail"),

    path("student/list/", views.StudentListView.as_view(), name="student-list"),
    path("student/create/", views.StudentCreateView.as_view(), name="student-create"),
    path("student/<int:pk>/update/", views.StudentUpdateView.as_view(), name="student-update"),
    path("student/<int:pk>/delete/", views.StudentDeleteView.as_view(), name="student-delete"),

    path("payment/", views.PaymentListView.as_view(), name='payment-list'),
    path('payment/create', views.PaymentCreateView.as_view(), name='payment-create'),
    path('payment/<int:pk>/delete', views.PaymentDeleteView.as_view(), name='payment-delete'),
    path('payment/<int:pk>/update', views.PaymentUpdateView.as_view(), name='payment-update'),
    path('payment/ajax-data/', views.ajax_payment_data, name='ajax-payment-data'),

    path("lead/list/", views.LeadListView.as_view(), name="lead-list"),
    path("lead/create/", views.LeadCreateView.as_view(), name="lead-create"),
    path("lead/<int:pk>/update/", views.LeadUpdateView.as_view(), name="lead-update"),
    path("lead/<int:pk>/delete/", views.LeadDeleteView.as_view(), name="lead-delete"),

    path("classroom/list/", views.ClassroomListView.as_view(), name="classroom-list"),
    path("classroom/create/", views.ClassroomCreateView.as_view(), name="classroom-create"),
    path("classroom/<int:pk>/update/", views.ClassroomUpdateView.as_view(), name="classroom-update"),
    path("classroom/<int:pk>/delete/", views.ClassroomDeleteView.as_view(), name="classroom-delete"),
    path("schedule/", views.schedule_view, name="schedule"),

    path("employee/list/", views.EmployeeListView.as_view(), name="employee-list"),
    path("employee/create/", views.EmployeeCreateView.as_view(), name="employee-create"),
    path("employee/<int:pk>/update/", views.EmployeeUpdateView.as_view(), name="employee-update"),
    path("employee/<int:pk>/delete/", views.EmployeeDeleteView.as_view(), name="employee-delete"),

    path("wages/list/", views.WagesListView.as_view(), name="wages-list"),
    path("wages/create/", views.WagesCreateView.as_view(), name="wages-create"),
    path("wages/<int:pk>/update/", views.WagesUpdateView.as_view(), name="wages-update"),
    path("wages/<int:pk>/delete/", views.WagesDeleteView.as_view(), name="wages-delete"),
    path('ajax/load-employees/', views.get_employees_by_role, name='get-employees-by-role'),

    path("api/attendance/", views.AttendanceListAPIView.as_view(), name="attendance-page"),
    path("attendance/<int:group_id>/", views.AttendanceView.as_view(), name="attendance-list"),
    path("api/attendance/save/", views.SaveAttendanceAPIView.as_view(), name="attendance-save"),
    path("api/groups/<int:group_id>/students/", views.GroupStudentsAPIView.as_view(), name="group-students"),
    
]

reception/urls.py
from django.urls import path
from reception import views
app_name = "reception"

urlpatterns = [
    path("", views.HomeView.as_view(), name='home'),

    path("course/list/", views.CourseListView.as_view(), name="course-list"),
    path("course/create/", views.CourseCreateView.as_view(), name="course-create"),
    path("courses/<int:pk>/groups/", views.CourseGroupListView.as_view(), name="course-groups"),
    path("course/<int:pk>/update/", views.CourseUpdateView.as_view(), name="course-update"),
    path("course/<int:pk>/delete/", views.CourseDeleteView.as_view(), name="course-delete"),


    path("group/list/", views.GroupListView.as_view(), name="group-list"),
    path("group/create/", views.GroupCreateView.as_view(), name="group-create"),
    path("groups/<int:pk>/students/", views.group_students, name="group-students"),
    path("group/<int:pk>/update/", views.GroupUpdateView.as_view(), name="group-update"),
    path("group/<int:pk>/delete/", views.GroupDeleteView.as_view(), name="group-delete"),


    path("student/list/", views.StudentListView.as_view(), name="student-list"),
    path("student/create/", views.StudentCreateView.as_view(), name="student-create"),
    path("student/<int:pk>/update/", views.StudentUpdateView.as_view(), name="student-update"),
    path("student/<int:pk>/delete/", views.StudentDeleteView.as_view(), name="student-delete"),


    path("lead/list/", views.LeadListView.as_view(), name="lead-list"),
    path("lead/create/", views.LeadCreateView.as_view(), name="lead-create"),
    path("lead/<int:pk>/update/", views.LeadUpdateView.as_view(), name="lead-update"),
    path("lead/<int:pk>/delete/", views.LeadDeleteView.as_view(), name="lead-delete"),

]

reception/models.py
from django.db import models

# Create your models here.

reception/views.py
from helpers.permissions import ReceptionPassesTestMixin
from common import models
from django.shortcuts import render ,get_object_or_404
from django.views import View
from django.views.generic import ListView , DeleteView
from django.urls import reverse_lazy   
from django.db.models import Q 
from common import models
from manager import forms
from common.models import Group,Course
from helpers.views import CreateView, UpdateView, DeleteView
from common.mixins import RoleRequiredMixin
from helpers import permissions



class HomeView(ReceptionPassesTestMixin,View):
    def get(self, request):
        return render(request, "reception/base/index.html")



class CourseListView(ListView):
    model = models.Course
    template_name = "reception/course/list.html"
    context_object_name = "courses"
    def get_queryset(self):
        queryset = models.Course.objects.all().order_by("id")
        search = self.request.GET.get("search", None)
        if search:
            queryset = queryset.filter(
                Q(name__icontains=search)
            )
        return queryset

class CourseGroupListView(ListView):
    model = Group
    template_name = "reception/course/course_groups.html"
    context_object_name = "groups"

    def get_queryset(self):
        course_id = self.kwargs["pk"]
        return Group.objects.filter(course_id=course_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["course"] = Course.objects.get(pk=self.kwargs["pk"])
        return context

class CourseCreateView(CreateView):
    model = models.Course
    form_class = forms.CourseForm
    context_object_name = "object"
    template_name = "reception/course/create.html"
    success_url ="reception:course-list"
    success_create_url ="reception:course-list"


class CourseUpdateView(UpdateView):
    model = models.Course
    form_class = forms.CourseForm
    context_object_name = "object"
    template_name = "reception/course/update.html"
    success_url = "reception:course-list"
    success_update_url = "reception:course-update"


class CourseDeleteView(DeleteView):
    model = models.Course
    success_url ="reception:course-list"


class GroupListView(ListView):
    model = models.Group
    template_name = "reception/group/list.html"
    context_object_name = "objects"
    paginate_by = 10
    def get_queryset(self):
        queryset = models.Group.objects.all().order_by("id")
        search = self.request.GET.get("search", None)
        
        if search:
            queryset = queryset.filter(
                Q(title__icontains=search))
        return queryset

def group_students(request, pk):
    group = get_object_or_404(Group, pk=pk)
    students = group.students.filter(status='ACTIVE') 
    context = {
        "group":group,
        "students":students
    }
    return render(request, "reception/group/group_students.html",context)

class GroupCreateView(CreateView):
    model = models.Group
    template_name = "reception/group/create.html"
    context_object_name = 'object'
    form_class = forms.GroupForm
    success_url ="reception:group-list"
    success_update_url ="reception:group-update" 


class GroupUpdateView(UpdateView):
    model = models.Group
    template_name = "reception/group/update.html"
    context_object_name = 'object'
    form_class = forms.GroupForm
    success_url ="reception:group-list"
    success_update_url ="reception:group-update"

class GroupDeleteView(DeleteView):
    model = models.Group
    success_url ="reception:group-list"

class StudentListView(ListView):
    model = models.Student
    template_name = "reception/student/list.html"
    context_object_name = "objects"
    paginate_by = 10
    def get_queryset(self):
        queryset = models.Student.objects.all().order_by("id")
        search = self.request.GET.get("search", None)
        
        if search:
            queryset = queryset.filter(
                Q(name__icontains=search) | Q(surname__icontains=search)
            )
        return queryset

class StudentCreateView(CreateView):
    model = models.Student
    form_class = forms.StudentForm
    template_name = "reception/student/create.html"
    context_object_name = "object"
    success_url = "reception:student-list"
    success_create_url = 'reception:student-create'
    
    
class StudentUpdateView(UpdateView):
    model = models.Student
    form_class = forms.StudentForm
    template_name = "reception/student/update.html"
    context_object_name = "object"
    success_url ="reception:student-list"
    success_create_url = 'reception:student-update'
    

class StudentDeleteView(DeleteView):
    model = models.Student
    success_url ='reception:student-list'



class LeadListView(ListView):
    model = models.Lead
    template_name = "reception/lead/list.html"
    context_object_name = "objects"
    paginate_by = 10
    def get_queryset(self):
        queryset = models.Lead.objects.all().order_by("id")
        search = self.request.GET.get("search", None)
        
        if search:
            queryset = queryset.filter(
                Q(name__icontains=search) | Q(surname__icontains=search)
            )
        return queryset

class LeadCreateView(CreateView):
    model = models.Lead
    form_class = forms.LeadForm
    template_name = "reception/lead/create.html"
    context_object_name = "object"
    success_url = "reception:lead-list"
    success_create_url = 'reception:lead-create'
    
    
class LeadUpdateView(UpdateView):
    model = models.Lead
    form_class = forms.LeadForm
    template_name = "reception/lead/update.html"
    context_object_name = "object"
    success_url ="reception:lead-list"
    success_create_url = 'reception:lead-update'
    

class LeadDeleteView(DeleteView):
    model = models.Lead
    success_url ='reception:lead-list'

templates/reception/group/create.html
{% extends "base/base.html" %} {% load static %} {% block content %}
<!--begin::Head-->
<!--end::Head-->
<!--begin::Body-->

<body
    id="kt_body"
    class="header-fixed header-mobile-fixed subheader-enabled subheader-fixed aside-enabled aside-fixed aside-minimize-hoverable page-loading"
>
    <!--begin::Main-->
    <!--begin::Header Mobile-->
    {% include "parts/header-mobile.html" %}
    <!--end::Header Mobile-->
    <div class="d-flex flex-column flex-root">
        <!--begin::Page-->
        <div class="d-flex flex-row flex-column-fluid page">
            <!--begin::Aside-->
            {% include "parts/aside.html" with menu_parent="group-all" menu_child="group-create" %}
            <!--end::Aside-->
            <!--begin::Wrapper-->
            <div class="d-flex flex-column flex-row-fluid wrapper" id="kt_wrapper">
                <!--begin::Header-->
                {% include "parts/header.html" %}
                <!--end::Header-->
                <!--begin::Content-->
                <div
                    class="content d-flex flex-column flex-column-fluid"
                    id="kt_content"
                >
                    <div class="d-flex flex-column-fluid">
                        <div class="container">
                            <div
                                class="card card-custom card-sticky"
                                id="kt_page_sticky_card"
                            >
                                <div class="card-header">
                                    <div class="card-title">
                                        <h3 class="card-label">
                                           Add group <i class="mr-2"></i>
                                        </h3>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <!--begin::Form-->
                                    <form class="form" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {% for field in form %}

                                        <div class="form-group row">
                                            <label class="col-form-label text-right col-lg-3 col-sm-12" for="{{field.auto_id}}">
                                                {% if field.field.required %}
                                                <b>{{field.label}}</b>
                                                {% else %}
                                                {{field.label}} 
                                                {% endif %}
                                            </label>
                                            <div class='col-lg-9 col-md-9 col-sm-12'>
                                                <span style="color:red;">{{field.errors}}</span>
                                                {{field}}
                                            </div>
                                        </div>
                                        {% endfor %}    
                                        <div class="card-footer">
                                            <div class="row">
                                                <div class="col-lg-3"></div>
                                                <div class="col-lg-9">
                                                    <button type="submit" class="btn btn-primary mr-2" name="save-create">Save and add new</button>
                                                    <button type="submit" class="btn btn-primary mr-2" name="saved">Save</button>
                                                    <a href="{% url 'reception:group-list' %}" class="btn btn-secondary"><span>Cancel</span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                            </div>

                        </div>
                        <!-- .container -->
                    </div>
                    <!-- .d-flex.flex-column-fluid -->
                </div>
                <!--end::Content-->
                <!--begin::Footer-->
                {% include "parts/footer.html" %}
                <!--end::Footer-->
            </div>
            <!--end::Wrapper-->
        </div>
        <!--end::Page-->
    </div>
    <!--end::Main-->
    <!-- begin::User Panel-->
    {% include "parts/user-panel.html" %}
    <!--begin::Quick Cart-->
    <!--end::Quick Cart-->
    <!--begin::Quick Panel-->
    <!--end::Quick Panel-->
    <!--begin::Chat Panel-->
    <!--end::Chat Panel-->
    <!--begin::Scrolltop-->
    {% include "parts/scrolltop.html" %}
    <!--end::Scrolltop-->
    <!--begin::Sticky Toolbar-->
    <!--end::Sticky Toolbar-->
    <!--begin::Demo Panel-->
    <!--end::Demo Panel-->
    <!--end::Page Scripts-->
</body>
<!--end::Body-->
{% endblock %}

templates/reception/group/group_students.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}

<body id="kt_body" class="header-fixed header-mobile-fixed subheader-enabled subheader-fixed aside-enabled aside-fixed aside-minimize-hoverable page-loading">

  {% include "parts/header-mobile.html" %}

  <div class="d-flex flex-column flex-root">
    <div class="d-flex flex-row flex-column-fluid page">

      {% include "parts/aside.html" with menu_parent="student-list" menu_child="student-all" %}

      <div class="d-flex flex-column flex-row-fluid wrapper" id="kt_wrapper">

        <div class="content d-flex flex-column flex-column-fluid" id="kt_content">

          <div class="d-flex flex-column-fluid">
            <div class="container">

              <div class="row">

                <div class="col-md-12">
                  <!--begin::Advance Table Widget 4-->
                  <div class="card card-custom card-stretch gutter-b">
                    <!--begin::Header-->
                    <div class="card-header border-0 py-5">

                      <h3 class="card-title align-items-start flex-column">
                        <span class="card-label font-weight-bolder text-dark">{{group.title}}'s students</span>
                        <small class='mt-2'>Total: {{objects | length}}</small>
                      </h3>
                    </div>
                    <!--end::Header-->
                    <!--begin::Body-->
                    <div class="card-body pt-0 pb-3">
                      <div class="tab-content">
                        <!--begin::Table-->
                        <div class="table-responsive">
                          {% if students %}
                          <table class="table table-head-custom table-head-bg table-borderless table-vertical-center">
                            <thead>
                              <tr class="text-left text-uppercase">
                                <th style="min-width: 100px">Full name</th>
                                <th style="min-width: 100px">Birth date</th>
                                <th style="min-width: 100px">Phone number</th>
                                <th style="min-width: 100px">Date_Joined</th>
                                <th style="min-width: 100px">Balance</th>
                                <th style="min-width: 100px">Status</th>
                                <th style="min-width: 100px">Actions</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for object in students %}
                              {% url 'manager:student-update' object.id as u %}
                              {% url 'manager:student-delete' object.id as d %}
                              <tr>
                                <td class="pl-0 py-6">
                                  <div class="d-flex align-items-center">
                                    <div class="mr-4 symbol symbol-40 symbol-light-success">
                                      <span class="symbol-label">{{ object.full_name|slice:':1' }}</span>
                                    </div>
                                    <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{object.full_name}}</span>      
                                  </div>
                                </td>
                                <td>
                                  <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{object.birth_date}}</span>
                                </td>
                                <td>
                                  <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{object.phone}}</span>
                                </td>
                                <td>
                                  <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{object.date_joined}}</span>
                                </td>
                                <td>
                                  <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{object.balance}}</span>
                                </td>
                                <td>
                                  <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{object.status}}</span>
                                </td>
                                <td nowrap="nowrap">
                                  {% include "parts/actions.html" with update_url=u delete_url=d %}
                                </td>
                              </tr>
                              {% endfor %}
                          </table>
                        </div>
                        <!--end::Table-->
                        {% else %}
                        {% include "parts/nothing-found.html" %}
                        {% endif %}
                      </div>
                      {% if page_obj.paginator.num_pages > 1 %}
                      {%include 'parts/pagination.html' %}
                      {% endif %}
                    </div>
                    <!--end::Body-->
                  </div>
                  <!--end::Advance Table Widget 4-->
                </div>
              </div>

            </div>
          </div>

        </div>

        {% include "parts/footer.html" %}
      </div>

    </div>
  </div>

</body>

{% endblock %}

templates/reception/group/list.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<!--begin::Head-->
<!--end::Head-->
<!--begin::Body-->
<body id="kt_body" class="header-fixed header-mobile-fixed subheader-enabled subheader-fixed aside-enabled aside-fixed aside-minimize-hoverable page-loading">
  <!--begin::Main-->
  <!--begin::Header Mobile-->
  {% include "parts/header-mobile.html" %}
  <!--end::Header Mobile-->
  <div class="d-flex flex-column flex-root">
    <!--begin::Page-->
    <div class="d-flex flex-row flex-column-fluid page">
      <!--begin::Aside-->
      {% include "parts/aside.html" with menu_parent='group-all' menu_child='group-list' %}
      <!--end::Aside-->
      <!--begin::Wrapper-->
      <div class="d-flex flex-column flex-row-fluid wrapper" id="kt_wrapper">
        <!--begin::Header-->
        {% include "parts/header.html" %}
        <!--end::Header-->
        <!--begin::Content-->
        <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
          <div class="d-flex flex-column-fluid">
            <div class="container">

              <div class="row">

                <div class="col-md-12">
                  <!--begin::Advance Table Widget 4-->
                  <div class="card card-custom card-stretch gutter-b">
                    <!--begin::Header-->
                    <div class="card-header border-0 py-5">

                      <h3 class="card-title align-items-start flex-column">
                        <span class="card-label font-weight-bolder text-dark">Groups</span>
                        <small class='mt-2'>Total: {{objects | length}}</small>
                        
                      </h3>
                    </div>
                    <!--end::Header-->
                    <!--begin::Body-->
                    <div class="card-body pt-0 pb-3">
                      <div class="tab-content">
                        <!--begin::Table-->
                        <div class="table-responsive">
                          {% if objects %}
                          <table class="table table-head-custom table-head-bg table-borderless table-vertical-center">
                            <thead>
                              <tr class="text-left text-uppercase">
                                <th style="min-width: 100px">Title</th>
                                <th style="min-width: 100px">Course</th>
                                <th style="min-width: 100px">Teacher</th>
                                <th style="min-width: 100px">Date started</th>
                                <th style="min-width: 100px">Lesson days</th>
                                <th style="min-width: 100px">Time</th>
                                <th style="min-width: 100px">Actions</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for object in objects %}
                              {% url 'manager:group-update' object.id as u %}
                              {% url 'manager:group-delete' object.id as d %}
                              <tr>
                                <td class="pl-0 py-6">
                                  <div class="d-flex align-items-center">
                                    <div class="mr-4 symbol symbol-40 symbol-light-success">
                                      <span class="symbol-label">{{ object.full_name|slice:':1' }}</span>
                                    </div>
                                    <a href="{% url 'reception:group-students' object.pk %}"><span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{object.title}}</span></a>
                                  </div>
                                </td>
                                
                                <td>
                                  <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{object.course}}</span>
                                </td>
                                <td>
                                  <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{object.teacher}}</span>
                                </td>
                                <td>
                                  <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{object.date_started}}</span>
                                </td>
                                <td>
                                  <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{object.lesson_days}}</span>
                                </td>
                                <td>
                                  <span class="text-dark-75 font-weight-bolder d-block font-size-lg">{{object.time}}</span>
                                </td>
                                <td nowrap="nowrap">
                                  {% include "parts/actions.html" with update_url=u delete_url=d %}
                                </td>
                              </tr>
                              {% endfor %}
                          </table>
                        </div>
                        <!--end::Table-->
                        {% else %}
                        {% include "parts/nothing-found.html" %}
                        {% endif %}
                      </div>
                      {% if page_obj.paginator.num_pages > 1 %}
                      {%include 'parts/pagination.html' %}
                      {% endif %}
                    </div>
                    <!--end::Body-->
                  </div>
                  <!--end::Advance Table Widget 4-->
                </div>
              </div>

            </div>
            <!-- .container -->
          </div> <!-- .d-flex.flex-column-fluid -->
        </div>
        <!--end::Content--> <!--begin::Footer-->
        {% include "parts/footer.html" %}
        <!--end::Footer-->
      </div>
      <!--end::Wrapper-->
    </div>
    <!--end::Page-->
  </div>
  <!--end::Main-->
  <!-- begin::User Panel-->
  {% include "parts/user-panel.html" %}
  <!--begin::Quick Cart-->
  <!--end::Quick Cart-->
  <!--begin::Quick Panel-->
  <!--end::Quick Panel-->
  <!--begin::Chat Panel-->
  <!--end::Chat Panel-->
  <!--begin::Scrolltop-->
  {% include "parts/scrolltop.html" %}
  <!--end::Scrolltop-->
  <!--begin::Sticky Toolbar-->
  <!--end::Sticky Toolbar-->
  <!--begin::Demo Panel-->
  <!--end::Demo Panel-->


</body>
<!--end::Body-->
{% endblock %}